### ISSUE TITLE
how to create room 

### ISSUE THREAD

**Issue by gaurav147-star** [DebjitPramanick/WhatsApp-Clone#1]
@DebjitPramanick facing problem ....how to create room...
![image](https://user-images.githubusercontent.com/78996081/147241123-01f00eac-c557-4e4e-84c6-d026c5e88ee5.png)
if i run in localhost
give me instruction how to run in locally

**Comment by DebjitPramanick** [comment]
1. Clone the repo
2. Run `npm install`
3. Run `npm start`
4. Click on the chat icon at top-left section to create room

**Comment by gaurav147-star** [comment]
Thanks @DebjitPramanick
